// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY gouanlin. DO NOT CHANGE IT.
// </auto-generated>

using System;
using System.Buffers.Binary;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Gal.Core {
	public static class RefWriterBytesEx {

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteInt8(this ref RefWriter<byte> self, sbyte value){ 
            self.Write((byte)value);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteBoolean(this ref RefWriter<byte> self, bool value){
            self.Write(value ? (byte)1 : (byte)0);
                    }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt16(this ref RefWriter<byte> self, UInt16 value) {
			var span = self.GetSpan(2);
            span[1] = (byte)(value >> 8);
			span[0] = (byte)value;
			self.Advance(2);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteInt16(this ref RefWriter<byte> self, Int16 value) {
			var span = self.GetSpan(2);
            span[1] = (byte)(value >> 8);
			span[0] = (byte)value;
			self.Advance(2);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteInt32(this ref RefWriter<byte> self, Int32 value) {
			Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(4)), !BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
            self.Advance(4);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt32(this ref RefWriter<byte> self, UInt32 value) {
			Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(4)), !BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
            self.Advance(4);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteInt64(this ref RefWriter<byte> self, Int64 value) {
			Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(8)), !BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
            self.Advance(8);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteUInt64(this ref RefWriter<byte> self, UInt64 value) {
			Unsafe.WriteUnaligned(ref MemoryMarshal.GetReference(self.GetSpan(8)), BitConverter.IsLittleEndian ? BinaryPrimitives.ReverseEndianness(value) : value);
            self.Advance(8);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static unsafe void WriteFloat(this ref RefWriter<byte> self, float value) => self.WriteInt32(*(int*) &value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static unsafe void WriteDouble(this ref RefWriter<byte> self, double value) => self.WriteInt64(*(long*) &value);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteVarUInt32(this ref RefWriter<byte> self, uint value) {
			while (value >= 0b10000000) {
				self.Write((byte)(value | 0b10000000));
				value >>= 7;
			}
			self.Write((byte)value);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteVarInt32(this ref RefWriter<byte> self, int value) => self.WriteVarUInt32(ZigZagUtils.EncodeZigZag32(value));

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteVarUInt64(this ref RefWriter<byte> self, ulong value) {
			while (value >= 0b10000000) {
				self.Write((byte)(value | 0b10000000));
				value >>= 7;
			}
			self.Write((byte)value);
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static void WriteVarInt64(this ref RefWriter<byte> self, long value){ 
            self.WriteVarUInt64(ZigZagUtils.EncodeZigZag64(value));
        }

        public static unsafe void WriteUtf8(this ref RefWriter<byte> self, string value, int bytesCount) {
			if (string.IsNullOrEmpty(value)) {
                return ;
			}
			fixed(char* source = value){
			    fixed (byte* target = self.GetSpan(bytesCount)) {
				    System.Text.Encoding.UTF8.GetBytes(source, value.Length, target, bytesCount);
			    }
            }
			self.Advance(bytesCount);
        }

        public static unsafe void WriteUtf8(this ref RefWriter<byte> self, string value) {
			if (string.IsNullOrEmpty(value)) {
				self.WriteInt16(0);
                return ;
			}
			
			var bytesCount   = System.Text.Encoding.UTF8.GetByteCount(value);
			self.WriteInt16((short)bytesCount);

			fixed(char* source = value){
			    fixed (byte* target = self.GetSpan(bytesCount)) {
				    System.Text.Encoding.UTF8.GetBytes(source, value.Length, target, bytesCount);
			    }
            }
			self.Advance(bytesCount);
        }
    }
}